name: Build with Docker
description: Build application with Docker
inputs:
  dockerfile_path:
    description: "Path do Dockerfile"
    required: false
    default: "Dockerfile"
  image_name:
    description: "Name of Dockerfile image"
    required: true
  tag_name:
    description: "Tag of Dockerfile image"
    required: false
runs:
  using: composite
  steps:
    - run: |

        echo "DOCKER_PATH=${{ inputs.{{dockerfile_path}} }}" >> $GITHUB_ENV
        echo "IMAGE=${{ inputs.{{image_name}} }}" >> $GITHUB_ENV

        if [ -z "${{ inputs.{{tag_name}} }}" ]; then
            echo "TAG=$(date +%s)" >> $GITHUB_ENV
        else
            echo "TAG=${{ inputs.{{tag_name}} }}" >> $GITHUB_ENV
        fi

        docker build . --file $DOCKER_PATH --tag "$IMAGE:$TAG" 
        docker images
      shell: bash
      temp: src/main/docker/Dockerfile.jvm
